#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'CodexAnalyzer_Preselection.exe /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/OutFiles_PreSelection/JOB_11-29-16/Main2/Codex1800.root   /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/../ROOT80X/Codex_1800.root'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
