#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'CodexAnalyzer_Preselection.exe /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/OutFiles_PreSelection/JOB_11-29-16/Main2/SingleTop.root /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/../ROOT80X/ST_t-channel_antitop_4f_leptonDecays.root /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/../ROOT80X/ST_t-channel_top_4f_leptonDecays.root /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/../ROOT80X/ST_tW_antitop_5f_inclusiveDecays.root /afs/cern.ch/work/m/mnaseri/work/13TeVAnalyses/DarkMatter_Codex/CMSSW_7_1_21_patch1/src/DarkMatter/RecoStudy/../ROOT80X/ST_tW_top_5f_inclusiveDecays.root'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
